package paymentprocessor

import (
	chimoney_international_payment_processor "usepolymer.co/infrastructure/payment_processor/chimoney"
	kora_local_payment_processor "usepolymer.co/infrastructure/payment_processor/kora"
)

var LocalPaymentProcessor = kora_local_payment_processor.LocalPaymentProcessor
var InternationalPaymentProcessor = chimoney_international_payment_processor.InternationalPaymentProcessor
