package dojah_identity_verification

var PolymerCACDetails = []byte(`{
        "RC_Number": "7295128",
        "Name_of_Company": "POLYMER SOFTWARE LTD",
        "Type_of_Company": "PRIVATE_COMPANY_LIMITED_BY_SHARES",
        "Date_of_Registration": "2024-01-10T21:28:23.321+00:00",
        "Branch_Address": "",
        "Email": "aceanyanwu02@gmail.com",
        "City": "1st Avenue Extension, Festac",
        "Classification": "",
        "Head_Office_Address": "",
        "LGA": "Lagos Mainland",
        "Number_of_Affiliates": "9",
        "Share_capital": "20000000",
        "Share_capital_in_words": "Twenty Million Naira",
        "State": "LAGOS",
        "Status": "ACTIVE",
        "ImageReport": "",
        "affiliates": [
            {
                "state": "FCT",
                "name": "Lekwa, Victoria",
                "companyRcNumber": "",
                "formerNationality": "",
                "status": "ACTIVE",
                "countryName": "NIGERIA",
                "identityType": "",
                "shareAllotted": "",
                "identityNumber": "",
                "accreditationnumber": "",
                "formerSurname": "",
                "formerFirstName": "",
                "formerOtherName": "",
                "otherDirectorshipDetails": "",
                "isChairman": "",
                "firstname": "Victoria",
                "uuid": "",
                "othername": "",
                "affiliateType": "DEPONENT",
                "isCorporate": "",
                "email": "lekwavi@gmail.com",
                "phoneNumber": "08094988443",
                "corporateName": "",
                "corporateRcNumber": "",
                "companyName": "",
                "rcNumber": "",
                "corporationName": "",
                "dateOfBirth": "",
                "dateOfAppointment": "2024-01-10T21:28:24.156+00:00",
                "lga": "Amac",
                "streetNumber": "",
                "nationality": "",
                "shareType": "",
                "postcode": "",
                "companyId": "",
                "gender": "",
                "formerName": "",
                "occupation": "",
                "dateOfTermination": "",
                "searchScore": "",
                "address": "1, Rima Street",
                "city": "Wuse zone 2",
                "id": "29849493",
                "surname": "Lekwa"
            },
            {
                "state": "LAGOS",
                "name": "Anyanwu-Ebere, Chiemekam",
                "companyRcNumber": "",
                "formerNationality": "",
                "status": "ACTIVE",
                "countryName": "NIGERIA",
                "identityType": "National ID Card",
                "shareAllotted": "20000000",
                "identityNumber": "84332598705",
                "accreditationnumber": "",
                "formerSurname": "",
                "formerFirstName": "",
                "formerOtherName": "",
                "otherDirectorshipDetails": "",
                "isChairman": "",
                "firstname": "Chiemekam",
                "uuid": "",
                "othername": "",
                "affiliateType": "PSC",
                "isCorporate": "",
                "email": "aceanyanwu02@gmail.com",
                "phoneNumber": "+2347061408434",
                "corporateName": "",
                "corporateRcNumber": "",
                "companyName": "",
                "rcNumber": "",
                "corporationName": "",
                "dateOfBirth": "",
                "dateOfAppointment": "2024-01-10T21:28:25.029+00:00",
                "lga": "Amuwo-Odofin",
                "streetNumber": "1",
                "nationality": "NIGERIA",
                "shareType": "ORDINARY",
                "postcode": "",
                "companyId": "",
                "gender": "MALE",
                "formerName": "",
                "occupation": "Software Engineer",
                "dateOfTermination": "",
                "searchScore": "",
                "address": "Vision Street",
                "city": "1st Avenue Extension, Festac",
                "id": "29849486",
                "surname": "Anyanwu-Ebere"
            },
            {
                "state": "LAGOS",
                "name": "Anyanwu-Ebere, Chiemekam",
                "companyRcNumber": "",
                "formerNationality": "",
                "status": "ACTIVE",
                "countryName": "NIGERIA",
                "identityType": "National ID Card",
                "shareAllotted": "20000000",
                "identityNumber": "84332598705",
                "accreditationnumber": "",
                "formerSurname": "",
                "formerFirstName": "",
                "formerOtherName": "",
                "otherDirectorshipDetails": "",
                "isChairman": "",
                "firstname": "Chiemekam",
                "uuid": "",
                "othername": "",
                "affiliateType": "SUBSCRIBER",
                "isCorporate": "",
                "email": "aceanyanwu02@gmail.com",
                "phoneNumber": "+2347061408434",
                "corporateName": "",
                "corporateRcNumber": "",
                "companyName": "",
                "rcNumber": "",
                "corporationName": "",
                "dateOfBirth": "",
                "dateOfAppointment": "2024-01-10T21:28:25.865+00:00",
                "lga": "Amuwo-Odofin",
                "streetNumber": "1",
                "nationality": "NIGERIA",
                "shareType": "ORDINARY",
                "postcode": "",
                "companyId": "",
                "gender": "MALE",
                "formerName": "",
                "occupation": "Software Engineer",
                "dateOfTermination": "",
                "searchScore": "",
                "address": "Vision Street",
                "city": "1st Avenue Extension, Festac",
                "id": "29849481",
                "surname": "Anyanwu-Ebere"
            },
            {
                "state": "LAGOS",
                "name": "Anyanwu-Ebere, Chizaram",
                "companyRcNumber": "",
                "formerNationality": "",
                "status": "ACTIVE",
                "countryName": "NIGERIA",
                "identityType": "National ID Card",
                "shareAllotted": "",
                "identityNumber": "30106354051",
                "accreditationnumber": "",
                "formerSurname": "",
                "formerFirstName": "",
                "formerOtherName": "",
                "otherDirectorshipDetails": "",
                "isChairman": "",
                "firstname": "Chizaram",
                "uuid": "",
                "othername": "",
                "affiliateType": "SECRETARY_COMPANY",
                "isCorporate": "",
                "email": "chizaramanyanwuebere@gmail.com",
                "phoneNumber": "+2349033693722",
                "corporateName": "",
                "corporateRcNumber": "",
                "companyName": "",
                "rcNumber": "",
                "corporationName": "",
                "dateOfBirth": "",
                "dateOfAppointment": "2024-01-10T21:28:26.720+00:00",
                "lga": "Amuwo-Odofin",
                "streetNumber": "1",
                "nationality": "NIGERIA",
                "shareType": "",
                "postcode": "",
                "companyId": "",
                "gender": "FEMALE",
                "formerName": "",
                "occupation": "Procurement Manager",
                "dateOfTermination": "",
                "searchScore": "",
                "address": "Vision Street",
                "city": "1st Avenue Extension, Festac",
                "id": "29849468",
                "surname": "Anyanwu-Ebere"
            },
            {
                "state": "LAGOS",
                "name": "Adegoke, Oluwatunmise Esther",
                "companyRcNumber": "",
                "formerNationality": "",
                "status": "ACTIVE",
                "countryName": "NIGERIA",
                "identityType": "National ID Card",
                "shareAllotted": "",
                "identityNumber": "1301019888",
                "accreditationnumber": "",
                "formerSurname": "",
                "formerFirstName": "",
                "formerOtherName": "",
                "otherDirectorshipDetails": "",
                "isChairman": "",
                "firstname": "Oluwatunmise",
                "uuid": "",
                "othername": "Esther",
                "affiliateType": "DIRECTOR",
                "isCorporate": "",
                "email": "oluwatunmiseadegokee@gmail.com",
                "phoneNumber": "+2348156959951",
                "corporateName": "",
                "corporateRcNumber": "",
                "companyName": "",
                "rcNumber": "",
                "corporationName": "",
                "dateOfBirth": "",
                "dateOfAppointment": "2024-01-10T21:28:27.724+00:00",
                "lga": "Mushin",
                "streetNumber": "154",
                "nationality": "NIGERIA",
                "shareType": "",
                "postcode": "",
                "companyId": "",
                "gender": "FEMALE",
                "formerName": "",
                "occupation": "Product Manager",
                "dateOfTermination": "",
                "searchScore": "",
                "address": "Isolo Road",
                "city": "Mushin",
                "id": "29849426",
                "surname": "Adegoke"
            },
            {
                "state": "LAGOS",
                "name": "Anyanwu-Ebere, Chizaram",
                "companyRcNumber": "",
                "formerNationality": "",
                "status": "ACTIVE",
                "countryName": "NIGERIA",
                "identityType": "National ID Card",
                "shareAllotted": "",
                "identityNumber": "30106354051",
                "accreditationnumber": "",
                "formerSurname": "",
                "formerFirstName": "",
                "formerOtherName": "",
                "otherDirectorshipDetails": "",
                "isChairman": "",
                "firstname": "Chizaram",
                "uuid": "",
                "othername": "",
                "affiliateType": "DIRECTOR",
                "isCorporate": "",
                "email": "chizaramanyanwuebere@gmail.com",
                "phoneNumber": "+2349033693722",
                "corporateName": "",
                "corporateRcNumber": "",
                "companyName": "",
                "rcNumber": "",
                "corporationName": "",
                "dateOfBirth": "",
                "dateOfAppointment": "2024-01-10T21:28:28.715+00:00",
                "lga": "Amuwo-Odofin",
                "streetNumber": "1",
                "nationality": "NIGERIA",
                "shareType": "",
                "postcode": "",
                "companyId": "",
                "gender": "FEMALE",
                "formerName": "",
                "occupation": "Procurement Manager",
                "dateOfTermination": "",
                "searchScore": "",
                "address": "Vision Street",
                "city": "1st Avenue Extension, Festac",
                "id": "29849380",
                "surname": "Anyanwu-Ebere"
            },
            {
                "state": "LAGOS",
                "name": "Anyanwu-Ebere, Chiemekam",
                "companyRcNumber": "",
                "formerNationality": "",
                "status": "ACTIVE",
                "countryName": "NIGERIA",
                "identityType": "National ID Card",
                "shareAllotted": "20000000",
                "identityNumber": "84332598705",
                "accreditationnumber": "",
                "formerSurname": "",
                "formerFirstName": "",
                "formerOtherName": "",
                "otherDirectorshipDetails": "",
                "isChairman": "",
                "firstname": "Chiemekam",
                "uuid": "",
                "othername": "",
                "affiliateType": "SHAREHOLDER",
                "isCorporate": "",
                "email": "aceanyanwu02@gmail.com",
                "phoneNumber": "+2347061408434",
                "corporateName": "",
                "corporateRcNumber": "",
                "companyName": "",
                "rcNumber": "",
                "corporationName": "",
                "dateOfBirth": "",
                "dateOfAppointment": "2024-01-10T21:28:29.645+00:00",
                "lga": "Amuwo-Odofin",
                "streetNumber": "1",
                "nationality": "NIGERIA",
                "shareType": "ORDINARY",
                "postcode": "",
                "companyId": "",
                "gender": "MALE",
                "formerName": "",
                "occupation": "Software Engineer",
                "dateOfTermination": "",
                "searchScore": "",
                "address": "Vision Street",
                "city": "1st Avenue Extension, Festac",
                "id": "29849336",
                "surname": "Anyanwu-Ebere"
            },
            {
                "state": "LAGOS",
                "name": "Anyanwu-Ebere, Chiemekam",
                "companyRcNumber": "",
                "formerNationality": "",
                "status": "ACTIVE",
                "countryName": "NIGERIA",
                "identityType": "National ID Card",
                "shareAllotted": "",
                "identityNumber": "84332598705",
                "accreditationnumber": "",
                "formerSurname": "",
                "formerFirstName": "",
                "formerOtherName": "",
                "otherDirectorshipDetails": "",
                "isChairman": "",
                "firstname": "Chiemekam",
                "uuid": "",
                "othername": "",
                "affiliateType": "DIRECTOR",
                "isCorporate": "",
                "email": "aceanyanwu02@gmail.com",
                "phoneNumber": "+2347061408434",
                "corporateName": "",
                "corporateRcNumber": "",
                "companyName": "",
                "rcNumber": "",
                "corporationName": "",
                "dateOfBirth": "",
                "dateOfAppointment": "2024-01-10T21:28:30.503+00:00",
                "lga": "Amuwo-Odofin",
                "streetNumber": "1",
                "nationality": "NIGERIA",
                "shareType": "",
                "postcode": "",
                "companyId": "",
                "gender": "MALE",
                "formerName": "",
                "occupation": "Software Engineer",
                "dateOfTermination": "",
                "searchScore": "",
                "address": "Vision Street",
                "city": "1st Avenue Extension, Festac",
                "id": "29849335",
                "surname": "Anyanwu-Ebere"
            },
            {
                "state": "FCT",
                "name": "OBOTSE, Cynthia",
                "companyRcNumber": "",
                "formerNationality": "",
                "status": "ACTIVE",
                "countryName": "NIGERIA",
                "identityType": "",
                "shareAllotted": "",
                "identityNumber": "",
                "accreditationnumber": "",
                "formerSurname": "",
                "formerFirstName": "",
                "formerOtherName": "",
                "otherDirectorshipDetails": "",
                "isChairman": "",
                "firstname": "Cynthia",
                "uuid": "",
                "othername": "",
                "affiliateType": "WITNESS",
                "isCorporate": "",
                "email": "Obotsecynthia@gmail.com",
                "phoneNumber": "08094988443",
                "corporateName": "",
                "corporateRcNumber": "",
                "companyName": "",
                "rcNumber": "",
                "corporationName": "",
                "dateOfBirth": "",
                "dateOfAppointment": "2024-01-10T21:28:31.341+00:00",
                "lga": "Amac",
                "streetNumber": "20",
                "nationality": "",
                "shareType": "",
                "postcode": "",
                "companyId": "",
                "gender": "",
                "formerName": "",
                "occupation": "Student",
                "dateOfTermination": "",
                "searchScore": "",
                "address": "Asamankese street",
                "city": "Wuse zone 2",
                "id": "29849308",
                "surname": "OBOTSE"
            }
        ]
}`)