# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - polymer-core-staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://polymerapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f2fe740a9d4f4dcc99132c352aeb24fc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9ebebe9f153246c2a4bfc79d16bdfc6e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: polymerapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f2fe740a9d4f4dcc99132c352aeb24fc }}/polymer-be:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'polymer-core-staging'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5f9ab6c182594bb6b30e3e33eb1418f8 }}
        images: 'polymerapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f2fe740a9d4f4dcc99132c352aeb24fc }}/polymer-be:${{ github.sha }}'